parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    content_api_key: '%env(CONTENT_API_KEY)%'
services:
    _defaults:
        autowire: true     
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\GoogleVisionService:
        arguments:
            $credentialsPath: '%env(GOOGLE_APPLICATION_CREDENTIALS)%'
    App\Service\ContentApiService:
        arguments:
            $apiKey: '%content_api_key%'

