name: deploy

on:
  workflow_run:
    workflows: [ci]
    types: [requested]
    branches:
      - main

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add environment variables
        run: |
          echo "${{ vars.APP_ENV }}" >> .env.local
          echo "${{ secrets.APP_SECRET }}" >> .env.local
          echo "${{ secrets.DATABASE_URL }}" >> .env.local
          echo "${{ secrets.MAILER_DSN }}" >> .env.local
          echo "${{ secrets.MAILER_RESEND_SECRET }}" >> .env.local
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env.local
          echo "${{ secrets.CONTENT_API_KEY }}" >> .env.local
          echo "${{ secrets.OPENAI_API_KEY }}" >> .env.local

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy
